### ISSUE TITLE
 could not find function "getDataset"

### ISSUE THREAD

**Issue by browningChen** [DiseaseTranscriptomicsLab/betAS#8]
> dataset <- getDataset(pathTables="*MATS.JC.txt", tool="rMATS")
Error in getDataset(pathTables = "*MATS.JC.txt", tool = "rMATS") : 
  could not find function "getDataset"
Hi,Ferreira,I thought I met question after I devtools::install_github("DiseaseTranscriptomicsLab/betAS") ,actually I couldnot find function getDataset in your packages too

**Comment by lecrop** [comment]
Hi, I had the same issue. If you install "betAS" following the code in "INSTALLATION" section (`devtools::install_github("marianaferreira/betAS")`), you are installing it from the "main branch". This function only appears in the "dev branch" so you need to install it with the next code: `devtools::install_github("marianaferreira/betAS@dev")`.

Make sure you use `library(betAS)`  to reload the functions after reinstalling to be able to access them.

**Comment by browningChen** [comment]
> Hi, I had the same issue. If you install "betAS" following the code in "INSTALLATION" section (`devtools::install_github("marianaferreira/betAS")`), you are installing it from the "main branch". This function only appears in the "dev branch" so you need to install it with the next code: `devtools::install_github("marianaferreira/betAS@dev")`.
> 
> Make sure you use `library(betAS)` to reload the functions after reinstalling to be able to access them.

thanku so much !!!

**Comment by ritamtbsilva** [comment]
Hello @browningChen,

Thank you for bringing this to our attention, and a special thanks to @lecrop for responding so promptly. You're absolutely correct. The `getDatasets` function, along with other associated functionalities for importing data from rMATS and whippet, is currently available in the development version of `betAS`.

We apologize for any confusion caused as our instructions were initially directed towards the main branch, which hasn’t been updated with these new features yet. Rest assured, we are planning to merge these changes into the main branch shortly.

In the interim, we have updated the README in both the development and the main branches, as well as the CMI tutorial, to clearly indicate that `betAS` should be downloaded from the development branch on GitHub, for the users that intend to use such features.

We appreciate your feedback and hope you find this package useful😊

**Comment by browningChen** [comment]
Thanks @ritamtbsilva  for your detailed response，As a beginner  in alternative splicing, your powerful visualization tools help me a lot, hope more people can take advantage of betAS
